### ISSUE TITLE
Main Jeopardy page

### ISSUE THREAD

**Issue by antman1p** [isislab/CSAW-CTF-2016-Quals#1]
Do you happen to have the main jeopardy page with the categories, hints, point values, etc..?  I would like to set it up locally for my team to practice.  Maybe the whole directory with the CSS, and scripts so I can just host it locally?

**Comment by kallsyms** [comment]
The 2016 challenge board is still available [here](https://archives.csaw.io/ctf2016/), and all of the challenge files with deployment scripts are in this repo. We use [CTFd](https://github.com/CTFd/CTFd), but the theme is private.
